---
abstract: 'A pure perl BibTeX parser'
author:
  - 'Gerhard Gossen <gerhard.gossen@googlemail.com>'
build_requires:
  File::Spec: 0
  IO::File: 0
  IO::String: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: BibTeX-Parser
no_index:
  directory:
    - inc
    - t
    - inc
    - t
requires:
  Text::Balanced: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.21
