---
abstract: 'A pure perl BibTeX parser'
author:
  - 'Gerhard Gossen <gerhard.gossen@googlemail.com>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.091940'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: BibTeX-Parser
requires:
  File::Spec: 0
  IO::File: 0
  IO::String: 0
  Test::More: 0
  Text::Balanced: 0
version: 0.3.1
